services:
  db:
    image: postgis/postgis:16-3.4
    container_name: earthquakes-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./db/volume:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  extractor:
    build: ./extractor
    container_name: extractor
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
      DATA_DIR: /data/usgs_earthquakes
      USGS_BASE_URL: https://earthquake.usgs.gov/fdsnws/event/1/query
    volumes:
      - ./data:/data
    restart: "no"

  spark:
    build: ./spark
    container_name: spark
    depends_on:
      db:
        condition: service_healthy
      extractor:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    volumes:
      - ./data:/data
