name: data-engineering
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - -e ./common
      - streamlit==1.50.0
      - psycopg2-binary==2.9.11
      - sqlmodel==0.0.27
      - geoalchemy2==0.18.0
      - python-dotenv==1.2.1
      - jupyter==1.1.1
      - matplotlib==3.9.3
      - seaborn==0.13.2
      - pandas==2.2.3