services:
  db:
    image: postgis/postgis:16-3.4   # PostgreSQL 16 + PostGIS 3.4 for geo features
    container_name: earthquakes-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PG_PORT}:5432"
    volumes:
      # Bind mount -> your project folder (visible on disk)
      - ./volume:/var/lib/postgresql
      # One-time init scripts. Anything in here runs on first boot (when no DB exists yet).
      - ./init:/docker-entrypoint-initdb.d:ro
    # basic health check for db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data: